### ISSUE TITLE
Protecting main branch from random commits

### ISSUE THREAD

**Issue by bountonw** [bountonw/translate#1]
@mattleff 

How do we protect the main branch from random commits. I want people to be able to issue pull requests, but I would like to limit those who can commit to a small group, including you.

**Comment by mattleff** [comment]
@bountonw Only those added to a public repository can commit to it. If the repository is public by default anyone can view, comment, and send PRs, but only those added to the repository and given permission can commit (and therefore merge PRs).

**Comment by bountonw** [comment]
Thank you.
