### ISSUE TITLE
Only run the build process when needed

### ISSUE THREAD

**Issue by bountonw** [bountonw/translate#101]
Part of #89 .

Build process should only run when files related to the PDFs, source or tooling, change).

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore

**Comment by bountonw** [comment]
@mattleff When updating Lao files `.md` or `lao.txt`, the Thai pdfs shouldn't be regenerated. And when updating Thai files, the Lao pdfs shouldn't be regenerated (future problem.)

**Comment by mattleff** [comment]
@bountonw GitHub is having [issues right now](https://www.githubstatus.com), so that's most of the difference, but I'll try to do this soon. 👍🏻
