### ISSUE TITLE
Create stripParagraphHeadings.lua script

### ISSUE THREAD

**Issue by bountonw** [bountonw/translate#115]
@tonyquicktech The `stripParagraphHeadings.lua` file should contain 1 function called `stripParagraphHeadings` that strips out the subheading level paragraph tags, i.e.  `## {PP 33.1}` , `## {MB 42.2}`, `## {GC 630.1}` along with the following blank line out of whatever file is fed it as a parameter. 

Something like this:
`stripParagraphHeadings(mdFile)`

We will use this as part of the various builds in building pdfs, htmls, txt exporting, epub format etc. 

Not sure where this file should go, but we can move it once there is a pull request. There will be many of these little scripts. Having things modular should help us not have to repeat ourselves. 

CC @mattleff for advice.

**Comment by tonyquicktech** [comment]
Opened a PR for this @bountonw @mattleff as the code is working on my machine, but having issues within github actions. #118

**Comment by mattleff** [comment]
Resolved with #176.
