### ISSUE TITLE
validation scripts only run when needed

### ISSUE THREAD

**Issue by bountonw** [bountonw/translate#12]
@mattleff 

This isn't urgent, but as we add more books, with book level validation scripts, we don't want scripts running at every commit and pull request if nothing has changed in the files that the script is running for. Is there a faster way of checking so that the script exits out if the files that apply to it haven't changed?

**Comment by mattleff** [comment]
@bountonw Yes, we can have the validation apply against only the changed files on the branch. But for now the runs are <30secs and GitHub actions time is free for public repositories, so this is probably pretty low priority, IMO.

**Comment by mattleff** [comment]
With #240 this should be fixed.
