### ISSUE TITLE
Transform poetry code blocks to block quotes 

### ISSUE THREAD

**Issue by mattleff** [bountonw/translate#174]
Initially just get content rendering, eventually fix the indentation and spacing.

**Comment by mattleff** [comment]
Follow up to #239 question:

> Approving since I need to edit LBF22 this morning. However there is a lot I don't understand. Will we be needing to revert the poetry in PP to `>` ? Will this allow for nested lines?

Check with Kenton about how this will work in InDesign.

**Comment by mattleff** [comment]
@kenton-r We have poetry in some of the books that is nested right now:

https://github.com/bountonw/translate/blob/6e9e2ad3bd2067a771d5a46cccdb69ae39e0c25f/th/PP/PP5/01_raw/PP70_th.md?plain=1#L235-L250

If we convert this to markdown blockquotes (`>`) how should we handle the nested lines so that we can process it correctly in InDesign? Markdown supports nested blockquotes (e.g., `> > whatever...`), but would having a style like `ParagraphStyle/Blockquote > Blockquote > Paragraph` even work in InDesign?

**Comment by kenton-r** [comment]
Yes we can try that. It should work it.

**Comment by mattleff** [comment]
@kenton-r I've generated an ICML with nested blockquotes. When you get a chance can you try it and make sure this type of nested styles will work in InDesign to reproduce the hierarchy present in the [source](https://github.com/bountonw/translate/blob/e15b4b61d713206a06533b689d9befcd12d8ed31/th/PP/PP5/01_raw/PP70_th.md?plain=1)? The deepest nesting is toward the [end of the chapter](https://github.com/bountonw/translate/blob/e15b4b61d713206a06533b689d9befcd12d8ed31/th/PP/PP5/01_raw/PP70_th.md?plain=1#L235-L262). 

[PP70_th.icml.zip](https://github.com/bountonw/translate/files/14986755/PP70_th.icml.zip)

**Comment by kenton-r** [comment]
Here is further work on the InDesign template that has nested block quotes and small version references to save space.

There are a few lines that are longer than the force break points. They are wrapped to the same margin as the initial indent with a balance option the InDesign has.

There is a "^" that proceeds a number 1 on page 7 and a missing block quote on page 8.

We also need to decide what Heading tag the chapter numbers are going to be. Before it was that subheads were Header2 and the chapter number was Header3. However this chapter for PP has subheads as Header3 and Chapter numbers also as Header3.
[Template_1a_PP.pdf](https://github.com/bountonw/translate/files/15058049/Template_1a_PP.pdf)

**Comment by mattleff** [comment]
@kenton-r Thanks for the update! The `^1` on page 7 is a footnote that wasn't getting processed correctly. I've fixed the missing blockquote on page 8. Here are new ICMLs with those fixes:

[PP70_th.icml.zip](https://github.com/bountonw/translate/files/15058881/PP70_th.icml.zip)

Are we good to move forward using this structure for the nested poetry blocks?

**Comment by kenton-r** [comment]
@bountonw We need Brian's feedback on the balanced lines for lines that are too long and the leaving them at the same indent level.

Sometime the wrapped line would also be indented slightly or the the next level.

I am working on the footnote

**Comment by bountonw** [comment]
We should be finished with editing sometime Wednesday.

**Comment by kenton-r** [comment]
This is an updated file with the footnote.
[Template_1b_PP.pdf](https://github.com/bountonw/translate/files/15061077/Template_1b_PP.pdf)
