### ISSUE TITLE
validate for proper paragraph tags

### ISSUE THREAD

**Issue by bountonw** [bountonw/translate#18]
When exporting to the press, especially, it is important that the paragraph tags are consistent. Yesterday in trying to create the paragraph level headings, I noticed dozens of improperly formed paragraph tags. 

```
{ PP \d{1,3}.\d}     # space before book code
{pp \d{1,3}.\d}     # lower case book code
{PP \d{1,3}. \d}     # space after period
{PP \d{1,3}.\d    # no closing brace
{PP\d{1,3}.\d     # no space after book code
```

In the past I have made the mistake of `{PP \d{1,3}:\d}` (using a colon instead of a period)
and when importing from someone else, I have had braces {}, brackets [], parenthesis (), mix-matched in every conceivable paring, and if copying form the EGW app, sometimes there are no surrounding punctuation but simply `PP \d{1,3}.\d `. 

(It is possible that there are pages with two digit paragraph counts and we might want to allow for that.  I think the validation for this should be at the book level, so we don't have to try and over think all of the potential correct codes. We simply define what a paragraph tag should look like for each book. This could be in the book level yaml even, then the validation script(s) can grab it when needed.

**Comment by bountonw** [comment]
It seems that there should be a place to define each book's paragraph code, i.e. `{PP #{1,3}.#}` `{MB #{1,3}.#}` or something like that.

**Comment by bountonw** [comment]
@mattleff Where should the definition of each book's paragraph code go so as not to repeat it for each chapter file?

**Comment by mattleff** [comment]
@bountonw I think in the [`metadata.yaml`](https://github.com/bountonw/translate/blob/latex-pdfs/th/MB/metadata.yaml) file in the volume root (which in the case of PP would be in [PP1](https://github.com/bountonw/translate/blob/latex-pdfs/th/PP/PP1/metadata.yaml), PP2, etc., since that is the volume). We could add like a custom `book_code` key with the paragraph code as the value. Wdyt?

**Comment by bountonw** [comment]
@mattleff I've spent 30 minutes trying to figure it out, but can't figure out how to move the metadata files into a clean PR. (BTW the book titles for the PP metadata files are referring to Mount of Blessings.)

**Comment by bountonw** [comment]
I am closing this as #215 has solved this issue. We can reopen it later if we want to tweak the algorithm or change the approach.
