### ISSUE TITLE
Validation test not ignoring footnote markers after closing parenthesis.

### ISSUE THREAD

**Issue by bountonw** [bountonw/translate#20]
@mattleff 

https://github.com/bountonw/translate/blob/c6784a2f56fdea13a2bddcade1ec7276474ef274/th/PP/scripts/validate-md.sh#L27

In PP25.md we have a closing parenthesis followed by a footnote marker `)[^1]` This is correct, but it causes the validation test to fail and remaining chapters are not tested.

**Comment by mattleff** [comment]
@bountonw Which branch are you testing this on? I'm seeing `Double spaces...` for PP25 on `PP2` but not closing parentheses...

**Comment by bountonw** [comment]
I'm on the road, but I believe I was on PP2 when I tested.

**Comment by bountonw** [comment]
@mattleff It is the validation warning on GitHub. Validation fails.
