### ISSUE TITLE
Fix subtitle conflicts in LBF

### ISSUE THREAD

**Issue by bountonw** [bountonw/translate#257]
Chapter 25 has `##` subheadings that are improperly nested. There are probably others. They should be `###` and should be nested under the paragraph numbers. There may be other chapters where this is a problem.

**Comment by bountonw** [comment]
Chapter 25 has been fixed. The rest of the chapters needs to be searched for conflicts. LBF does not have very many subheadings, but there are 1-2 chapters that this is still an issue for.

**Comment by mattleff** [comment]
@bountonw I've searched for any instances of `##` headings that aren't references code using this pattern: `^## [^\{]`. There aren't any in the LBF files on `main` branch, so I think we can close this.

**Comment by bountonw** [comment]
Ok

**Comment by bountonw** [comment]
@mattleff I think there may be some ### levels that are improperly nested.

**Comment by mattleff** [comment]
@bountonw I'm currently only seeing `###` headings in LBF25 + LBF37. LBF25 is fixed already, and LBF37 doesn't have the `##` headings yet (so they aren't improperly nested).
