### ISSUE TITLE
PDF LBF_202405232200 (Round 2)

### ISSUE THREAD

**Issue by bountonw** [bountonw/translate#296]
**Old issues:**
- [ ] ch 3. p 8.2.3 Copying เธสะโลนิกา gives เธสะโลนิก า (a space before the last character.) This is an improvement over we were getting เธิ์สะโลน์กา
- [x] 7.2 whole paragraph. Seems bloated พระ-วจนะ can be hyphenated if that would relieve some of the tension. ปีแล้วปีเล่า on the first line does not need hyphenated, but it is an idiomatic phrase that fits nicely together. [It really should be together]. มุ่งหมาย should stay together.
- [x] 9.1.6 The italicized word. I thought we fixed this, but I don't see any change. Following is the text of the problem copied from the last issue. _In English, all words are surrounded by spaces. However, this is not the case for Thai and italicized words in the middle of a phrase may pose an aesthetic problem. Is there a way of inserting a tiny space before and after italicized words that are surrounded by other text (and to not add the space if a real space is already there?_

**New issues:**
- [x] **TEXT UPDATED:** Foreword. p iii.1 Fixed spelling of ประวัติศาสตร์, Changed "to" to en-dash in date range. Updated spelling for Minneapolis and Minnesota. 
- [x] **TEXT UPDATED:** Foreward. p iii.2 Changed wording. Fixed spelling of นิตยสาร twice. Made the English titles of the magazine italics.
- [x] **URGENT** Foreword. p iii.2 คริสตจักร must not be split. It can be hyphenated as คริสต-จักร
- [x] **TEXT UPDATED:** Foreward. p iii.3 
- [x] **TEXT UPDATED:** ch 4. p 11.1.4 (ดู โรม 1:16...
- [x] **TEXT UPDATED:** ch 5. p 14.1.1 Rephrased. Removed space.
- [x] ch 5. p 15.2 1st 3 lines are very bloated. Next 3 lines look bloated. Second to the last line looks crowded. Reminder that พระ-เจ้า and พระ-องค์ are common hyphenation points in Thai Bibles. 
- [x] **TEXT UPDATED:** ch 5. p 16.1.6 Removed words.
- [x] **TEXT UPDATED:** ch 6. p 17.4 Move footnote into text as parenthetical comment.
- [x] ch 6. p 18.2 First lines bloated, last lines crowded.
- [x] **TEXT UPDATED:** ch 7. p 19.2.2 Deleted words
- [x] ch 7. p 19.2.4 Very bloated. This may change as text was deleted earlier in the paragraph.
- [x] ch 7. p 19.3.5 Very stretched. พระ-องค์ should be hyphenated.
- [x] **URGENT:** ch 7. p 20.1/2 เปโตร can't be split. This is in the forbidden-breaks dictionary.
- [x] **Important:** ch 7. p 20.2.1 พลา-นุภาพ This word either needs a hyphen or put on one line. We talked about this earlier, but I don't remember the conclusion.
- [x] **TEXT UPDATED:** ch 7. p 21.3.7. Added a word for clarity.
- [x] ch 7. p 22.2.4 line is very stretched
- [x] **CHAPTER TITLE UPDATED:** ch 9. p 26. Updated title.
- [x] Check change of chapter title chapter 9 in TOC.
- [x] ch 9. p 28.1.3 พระ-คัมภีร์ can be hyphenated to avoid the stretch on line 2.
- [x] **Important:** ch 9. p 28.2.4/5 ฤทธา-นุภาพ This word either must be hyphenated or be on the same line. It can't be split without a hyphen.
- [x] **TEXT UPDATED:** ch 10. p 33.2.6 Fixed พระพระ 
- [x] ch 12. p 39.2.2/3 Line two is stretched. Suggest พระ-บัญญัติ
- [x] **Important:**ch 12. p 39.2.8 เฉลยธรรมบัญญัติ needs a hyphen or to be on one line. เฉลย\~ธรรม\~\~บัญ~\~\~ญัติ
- [x] **Important:**ch 12. p 40.0.5/6 เฉลยธรรมบัญญัติ needs a hyphen or to be on one line. เฉลย\~ธรรม\~\~บัญ~\~\ญัติ. Keeping it as it is and just adding a hyphen is ok.
- [x] **VERY URGENT:** ch 12. p 40.1.4/5 ชีวิต is a common Thai word and must not be split or hyphenated. 
- [x] **TEXT UPDATED:** ch 12. p 40.2.1 space added/space removed
- [x] **TEXT UPDATED:** ch 13. p 43.2.7 Added grammar word
- [x] **TEXT UPDATED:** ch 13. p 45.2.3-4 Added word, closed space, added space. พระ\~ธรรม|โค\~โล\~สี. In case hyphenation become necessary.
- [x] ** URGENT:** ch 14. p 49.2.2/3 เอวา can't be split, nor can it be hyphenated.
- [x] ch 14. p 50.4.1/2 ข้าพระองค์ is split over two lines. It should either have a hyphen or be on one line ข้า-พระ-องค์ equal hyphen points in this case. 
- [x] **TEXT UPDATED:** ch 14. p 50.5.2/3 Bold changed to italics
- [x] ch 15. p 51.1-3 The first two lines are very stretches. Bringing พระ- up from line 3 should help.
- [x] ch 16. p 54.2.1 พระ- First line is way too stretched
- [x] **IMPORTANT** ch 17. p 62.1.6/7 ศีล-ธรรม needs hyphenating or on the same line.
- [x] ch 17. p 63.3.1 พระ- First line is way too stretched
- [x] ch 18. p 68.2.4/5 แตะต้อง should ideally be on the same line. Also, line 4 is very stretched.
- [x] ch 20. p 73.1.1-3 พระวิญญาณ on line 3 is stretching lines 1 and 2. สาวก on line 2 should move up and พระ\~วิญ\~\~ญาน should be hyphenated.
- [x] ch 20. p 73.2.1/2 พระ-สุร-เสียง we can take either the first or the first and second syllables up so that the first line isn't so stretched.
- [x] **TEXT UPDATED:** ch 20. p 74.2.3 fixed typo ขั้น to ขึ้น
- [x] **Important:** ch 20. p 74.2.3/4 ฤทธานุ-ภาพ or ฤทธา-นุภาพ This word needs a hyphen or needs to be on the same line.
- [x] ch 20. p 74.2.6 พงศ์-กษัตริย์ is a possible hyphenation point if needed. Line 5 is very stretched and depending on what is done with ฤทธานุภาพ you may need this option.
- [x] **TEXT UPDATED:** ch 20. p 74.3.5 changed wording.
- [x] ch 20. p 75.1.4 line is stretched
- [x] - [ ] **TEXT UPDATED:** ch 20. p 75.2.4 changed wording.
- [x] - [ ] **TEXT UPDATED:** ch 20. p 76.0.10 Added word.
- [x] ch 20. p 76.3.2 line is stretched พระ\~วิญ\~\~ญาณ
- [x] ch 20. p 77.1.3 พระ-วิญญาณ This is stretching the previous two lines. This would also solve the next problem.
- [x] **Important:** ch 20. p 77.1.3/2 ฤทธา\~นุ\~ภาพ needs a hyphen or needs to be on the same line. 
- [x] **Important:** ch 20. p 77.1.10/11  ฤทธา\~นุ\~ภาพ needs a hyphen or needs to be on the same line. 
- [x] ch 20. p 77.2.3 line is stretched พระ-
- [x] ch 20. p 78.1.1 line is very stretched. Not sure if it is because แสดง  is too big to bring up, which in that case there is nothing we can do, or if there is a large word later on that needs to be hyphenated in order to free up the paragraph.
- [x] ch 21. p 80.2 paragraph seems bloated.  Probably due to พระเจ้าพระบิดา in line 5. พระ-เจ้า/พระ-บิดา are all valid
- [x] ch 22. p 82.2.3-8 are bloated. พระ\~วิญ\~\~ญาณ on line 6 and 7 might help
- [x] ch 22. p 87.1.10 line is stretched. สัม-ฤทธิ์ 2 lines down is an option
- [x] ch 23. p 89.1.1 stretched. สม-บูรณ์แบบ
- [x] **Important:** ch 24. p 91.1.3/4 พลา\~นุ\~ภาพ Needs a hyphen or needs to be on the same line. 
- [x] ** URGENT:** ch 25. p 98.1.3/4 ซาราห์ must not be split. It may be hyphenated ซา-ราห์ if absolutely necessary.
- [x] [ ] **URGENT:** ch 26. p 102.1.1/2 เปโตร can't be split. This is in the forbidden-breaks dictionary.
- [x] **URGENT:** ch 26. p 102.2.2/3 เอลีซา can't be split without a hyphen. Hyphen is not preferred, but if necessary เอ\~ลี\~ซา.
- [x] ch 26. p 102.3 Entire paragraph seems bloated. Line 6/7 องค์พระผู้เป็นเจ้า shouldn't be split without hyphens. And if we are going to hyphenate anyway, I suggest we look for other พระ words that might be causing the pressure buildup.
- [x] ch 27. p 108.1.1/2 stretched. พระ-
- [x] ch 27. p 108.2.2 stretched. ปรา-กฎ on lines 3/4 is possible
- [x] ch 27. p 108.2.4 stretched. พระ-เยซู
- [x] ch 27. p 108.3 paragraph bloated
- [x] **URGENT:** ch 28. p 110.1.1/2 โลกีย-วิสัย This is one word. Either hyphenate or keep on the same line.
- [x] ch 29. p 115.1.1-4 lines stretched. Probably something later that needs hypenating to release the pressure.
- [x] **TEXT UPDATED** ch 29. p 116.0.1 delete word.
- [x] ch 29. p 117.1.1 stretched. "พระ-วิญญาณ or would that make it too crowded?
- [x] **TEXT UPDATED** ch 29. p 118.0.1 change wording
- [x] ch 29. p 118.2.1 stretched. อัศ-จรรย์ is a possible hyphenation.
- [x] ch 30. p 120.1.1 Would really be nice to get หมิ่น  on the first line if it will fit without squishing things too much. [Not possible]
- [x] ch 30. p 121.1.5 very stretch. ข้า-พระองค์ on lines 7/8 either needs hyphenated or on the same line. Suggest hyphenating as ข้าพระ-องค์. สันติ-สุข is also possible on line 6.
- [x] ch 30. p 122.0.3/4  ฤทธา-นุภาพ needs a hyphen. 
- [x] ch 30. p 122.1.1-4 bloated. In comparison the last few lines looked squished.
- [x] ch 30. p 122.2.1/2 First line is stretched. สา-มารถ is a legitimate hyphenation point. I think พระ-ดำรัส on the last line might be bloating the paragraph.
- [x] ch 30. p 123.0.3-5 stretched, especially line 3. There are several พระ- words in the paragraph. ปฐม-กาล is also possible. Last line พระ-วจนะ. There are other bloated lines in the paragraph.
- [x] ch 31. p 124.1.7 stretched. There are many พระ-องค์ words, maybe one of them is causing the pressure build up.
- [x] ch 31. p 125.1.6 stretched
- [x] ch 31. p 125.2.1 very stretched พระ-พักตร์
- [x] ch 31. p 125.2.6 very strecthed ประ-ทาน
- [x] **TEXT UPDATED** ch 31. p 126.1.6 Two thousand changed to 2,000
- [x] ch 31. p 127.1.6 stretched สถา-ปนา [not possible]
- [x] ch 32. p 129.1.1/2 first line stretched. ประ-ทาน พระ-องค์ 
- [x] **TEXT UPDATED:** ch 32. p 129.3.2 changed double quotes to single quotes. 
- [x] ch 32. p 129.3.5 very stretched. พระ-วจนะ
- [x] ch 32. p 129.4.1 very stretched. อานุ-ภาพ on line 2. พระ-วจนะ on line 3.
- [x] ch 32. p 129.4.7/130.0.1 stretched. พระ-องค์
- [x] ch 32. p 130.1.3 stretched. สา-มารถ
- [x] ch 32. p 130.1.4 stretched รับ|ประ-ทาน on lines 5 and 6. No hyphen needed after รับ and ประ-ทาน is commonly hyphenated.
- [x] **TEXT UPDATED:** ch 32. p 130.1.6 อาการ changed to อาหาร
- [x] ch 33. p 131.3.1,3 stretched. several พระ- words in paragraph.
- [x] **TEXT UPDATED:** ch 33. p 132.0.3 standardized spelling
- [x] ch 33. p 132.2.2 stretched. Not sure why this is stretched, and what the solution is.
- [x] **TEXT UPDATED:** ch 33. p 132.2.3 deleted word
- [x] ch 34. p 134.1.4/5 stretched. ถ่าย|ทอด doesn't need a hyphen and can be split across lines.
- [x] ch 34. p 135.1.4 stretched. I think ประ-ดับ on line 6 is what is causing the stretch.
- [x] ch 34. p 136.1.1,3 stretched. ตระ-หนัก
- [x] ch 34. p 136.2.1 stretched. พระ-องค์
- [x] ch 34. p 137.0.12/13 องค์พระผู้-เป็นเจ้า This is hyphenated in the TNCV version. The hyphen can occur at any syllable, but it is necessary.
- [x] **TEXT UPDATED** ch 34. p 138.0.9-10 ถ้อยคำ changed to พระวจนะ 3 times.
- [x] **TEXT UPDATED** ch 34. p 138.1.1 ถ้อยคำ changed to พระวจนะ
- [x] ch 34. p 138.2.3/4 stretched. พระ-คัมภีร์
- [x] **TEXT UPDATED** ch 35. p 140.1.2,4 Changed ถึง to ยัง. Added ดู. 
- [x] **TEXT UPDATED** ch 35. p 140.2.4 Changed wording
- [x] ch 35. p 141.3.3 stretched. พระ-องค์ several lines down might help.
- [x] ch 36. p 143.2.1-2 stretched. Possibly ธรรม|บัญญัติ later on line 4/5 (without a hyphen) might help? Or perhaps ธรรมบัญ-ญัติ on line 3 would minimize the contrast between lines 2 and 3.
- [x] **VERY URGENT:** ch 36. p 145.1.4/5 ก|ลุ่ม is a one syllable word and must not be split and can not be hyphenated. It must be on either on line 4 or 5.
- [x] ch 36. p 146.3.4 changed word for law.
- [x] ch 36. p 146.3.5 stretched. พระ-ทัย
- [x] ch 36. p 147.0.3/4 องค์-พระเยซูคริสต์เจ้า is hyphenated in TNCV.
- [x] **URGENT:** ch 37. p 148.3.3/4 ฤทธา\~นุ\~ภาพ long word with two hyphenation points.
- [x] **IMPORTANT:** ch 37. p 149.2.4/5 ราช-กิจ is one word. Should be hyphenated or put on one line.
- [x] ch 37. p 150.3.4 stretched. พระ-เยซู on line 6/7.
- [x] ch 37. p 152.2.2 stretched. พระ\~วิญ\~\~ญาณ on line 5 is probably the issue.
- [x] ch 37. p 153.2.1 stretched พระ-เจ้า
- [x] ch 39. p 160.1.1,3 stretched พระ-เจ้า
- [x] **IMPORTANT:** ch 39. p 160.2.6/7 ฤทธา\~นุ\~ภาพ This is one word and needs a hyphen or needs to be on one line.
- [x] **IMPORTANT:** ch 39. p 162.2.1/2 ฤทธา\~นุ\~ภาพ This is one word and needs a hyphen or needs to be on one line.
- [x] **IMPORTANT:** ch 41. p 168.1.1/2 ราช-กิจ is one word. Should be hyphenated or put on one line.
- [x] ch 41. p 168.2.10 stretched พระ-องค์
- [x] **IMPORTANT:** ch 41. p 169.2.3/4 องค์\~พระ\~ผู้\~เป็น\~เจ้า Should be hyphenated. Fortunately, there are many hyphenation points.
- [x] ch 41. p 171.2.3 stretched พระ-องค์
- [x] **IMPORTANT:** ch 41. p 172.1.2/3 องค์\~พระ\~ผู้\~เป็น\~เจ้า Should be hyphenated. Fortunately, there are many hyphenation points.
- [x] **TEXT UPDATE:** ch 42. p 174.1.5-6 Closed space. Added phrase (which will end up making the paragraph longer by one line.) Added grammar word.
- [x] **IMPORTANT:** ch 42. p 175.1.5/6 พระ\~เย\~\~ซู\~คริสต์ This is hyphenated in the TNCV, which we are using as the standard for hyphenation. The entire phrase is a minefield for hyphenation. (`|` refers to a word break). และ|พระ\~โล\~\~หิต|ของ|พระ\~เย\~\~ซู\~คริสต์|พระ\~บุตร|ของ|พระ\~องค์
- [x] ch 42. p 176.2.2 stretched พระ-องค์
- [x] ch 42. p 177.1.1 stretched อัศ-จรรย์
- [x] ch 43. p 178.1.7 stretched. Possibly because of พระ-เกียรติ on the last line.
- [x] **VERY IMPORTANT** ch 44. p 179.1.1/2 ประ-โยค is one word and can't be split without a hyphen.
- [x] **TEXT UPDATED:** ch 44. p 179.1.2 Closed space. If necessary, we can bring it back, but ideally, it should be closed.
- [x] **TEXT UPDATED:** ch 44. p 180.1.2. Changed word.
- [x] ch 44. p 180.1.9 stretched. หมายถึง Ideally should be on the same line. This would fix the stretching on the second to the last line.
- [x] ch 44. p 180.2.1 very stretched. พระ\~วิญ\~\~ญาณ
- [x] **IMPORTANT** ch 44. p 180.2.4/5 นิรันดร์-กาล is one word and needs to be hyphenated or put on the same line.
- [x] **IMPORTANT:** ch 44. p 180.2.10/11 ฤทธา\~นุ\~ภาพ This is one word and needs a hyphen or needs to be on one line.
- [x] **TEXT UPDATED:** ch 44. p 180.2.12 added royal word
- [x] ch 44. p 181.1.6 seems scrunched with the following lines seeming stretched. Suggest อัคร-ทูต
- [x] **TEXT UPDATED:** ch 44. p 181.2.7. Fixed typo. Removed double มี.
- [x] **TEXT UPDATED: ** ch 44. p 181.2.8 Added grammar word
- [x] **IMPORTANT** ch 44. p 182.0.4/5 พระ\~เย\~\~ซู\~คริสต์
- [x] ch 45. p 183.1.3 very stretched. ธรรม-ชาติ on line 5. (Line 5 is also very scrunched.)
- [x] ch 45. p 183.2.1-2,4 stretched พระ-องค์, ประ-เสริฐ
- [x] **TEXT UPDATED:** ch 45. p 185.1.2 Added honorific.
- [x] ch 45. p 186.2.3/4 stretched เหมาะ-สม
- [x] **TEXT UPDATED:** ch 45. p 186.2.6. Added grammar word
- [x] **TEXT UPDATED:** ch 45. p 186.2.11. Deleted 2 words not in the source document.
- [x] ch 45. p 187.1.2/3 stretched  พระ\~บัญ\~\~ญัติ
- [x] ch 45. p 188.0.3-4 stretched.
- [x] **TEXT UPDATED:** ch 45. p 188.0.6 Delete extra royal word.
- [x] ch 46. p 189.1.1 stretched. เป-โตร is hyphenable if necessary. Depending on how many stretched/scrunched lines we want for the document.
- [x] **IMPORTANT** ch 46. p 190.1.7/8 พญา-มาร is one word and needs hyphenated or put on one line.
- [x] ch 47. p 192.2.1 stretched. สา-มารถ
- [x] ch 47. p 193.1.3-4,7 stretched พระ-พร?
- [x] ch 47. p 193.2.1 stretched. จิต\~วิญ\~ญาณ, พยา\~ยาม
- [x] **TEXT UPDATED:** ch 47. p 193.3.4 added grammar word
- [x] ch 47. p 195.1.2 stretched พระ-องค์
- [x] ch 47. p 195.1.12 stretched. Not sure why. No obvious reason.
- [x] ch 47. p 196.1.5 stretched. พระ\~วิญ\~\~ญาณ
- [x] ch 48. p 197.2.2 stretched. แน่|นอน
- [x] **VERY IMPORTANT** ch 48. p 198.2.1/2 กระ-ทำ is one word and can't be split without a hyphen
- [x] ch 48. p 198.3.3,5,7-8 stretched. อธิษ-ฐาน
- [x] ch 48. p 198.4.3 stretched
- [x] ch 48. p 199.1 Several lines stretched. ปัญ\~\~ญา\~จารย์ on the last line.
- [x] **IMPORTANT** ch 48. p 199.2.2/3 พระเยซู-คริสต์ Needs hyphenating or on the same line.
- [x] ch 48. p 200.1.1 stretched. พระ-บัญญัติ
- [x] **IMPORTANT:** ch 49. p 201..2.4/5 องค์\~พระ\~ผู้\~เป็น\~เจ้า Should be hyphenated.
- [x] ch 49. p 202.2.1 stretched. ประ-ชาชน. Actually the whole paragraph looks bloated. อิส-ยาห์ is a possible solution, but maybe not ideal to end the book on.

**Comment by kenton-r** [comment]
ch 3. p 8.2.3 - This one I can not reproduce. When I copy it, it is correct.
9.1.6 - This already has a small space character added.

I was not able to fix the other none checked noted correction. This means that in working with several different ways to correct it, they all produced something worse than how it is current formatted.

**Comment by bountonw** [comment]
Except for the issue of copying PDF text, all issues have been addressed. If there was no change, it means that it wasn’t fixable.
