### ISSUE TITLE
Versioning of .md translation files

### ISSUE THREAD

**Issue by bountonw** [bountonw/translate#30]
We need a way to inform the public regarding what version of the document they are looking at. As public-facing documents are edited occasionally, how does the general public know if they have the latest version?

**Comment by tonyquicktech** [comment]
Would this be in the generated PDF files, or in the repos?

If it was in the PDF files, then it might be possible to add this to the workflow automatically in a "Version x.x" format. However, that doesn't solve the ongoing issue - people still won't know what the latest version is unless they specifically go to a reference page. This could potentially be mitigated by generating a page in the beginning of every file listing the version number, date of generation, and a link to a readme file somewhere in github that would be updated whenever a file is updated.

If its only github, and no need for that in the PDFs, then perhaps just an auto updated readme file in the directory of each book?
