### ISSUE TITLE
Add 1SM chapters on revival

### ISSUE THREAD

**Issue by bountonw** [bountonw/translate#339]
Add chapters 16 and 17 of 1 Selected Messages to a folder called `misc`. The paragraphs should be encoded with the regular 1SM tags.

**Comment by bountonw** [comment]
@tonyquicktech Is this something that you can do?

**Comment by tonyquicktech** [comment]
Sure

**Comment by bountonw** [comment]
Yes. And Thai. There is a separate issue for the Thai.

**Comment by tonyquicktech** [comment]
This is done :)

**Comment by bountonw** [comment]
@tonyquicktech yes. Thank you! I am midway through editing the Thai translation of one of the paragraphs that I wanted to include in this PR.

**Comment by tonyquicktech** [comment]
Roger that
