### ISSUE TITLE
Add yaml in Thai PP files to point to the English source.

### ISSUE THREAD

**Issue by bountonw** [bountonw/translate#34]
This is dependent on #76.

**Comment by tonyquicktech** [comment]
@bountonw I think we already resolved this one some time ago?

**Comment by bountonw** [comment]
I'm not sure. After the weekend, maybe @mattleff can clarify.

**Comment by bountonw** [comment]
The goal is for a future module to be able to have bi-lingual resources.

**Comment by tonyquicktech** [comment]
Roger that. Happy Sabbath!

**Comment by mattleff** [comment]
@bountonw @tonyquicktech My suggestion would be to rely on convention instead of configuration. That is, use the fact that we name all the `.md` files in a standard pattern and use the pattern parts to find the associated file(s). Wdyt?

**Comment by bountonw** [comment]
Note to self: wdyt = What do you think

**Comment by mattleff** [comment]
I don't hear any objection 😀, so I think we can close this.

**Comment by bountonw** [comment]
It is because I didn't understand the comment. But if the solution of bilingual printing and referencing source paragraphs as an aid in translation does not include new yaml, I have no objection. 😀

**Comment by mattleff** [comment]
Yup, I think we can do what we need as things are. 😁
