### ISSUE TITLE
Add 1SM16_th.md file in /th/misc/01_raw folder

### ISSUE THREAD

**Issue by bountonw** [bountonw/translate#340]
Populate the file with a yaml header and paragraphs as per the other books. Include the Thai paragraphs translated here.

- [x] ในหมู่พวกเรา การฟื้นฟูจิตวิญญาณให้สอดคล้องกับพระลักษณะของพระเจ้าอย่างแท้จริงเป็นสิ่งที่จำเป็นและเร่งด่วนที่สุด การแสวงหาสิ่งนี้ควรเป็นงานอันดับแรกของเรา เราต้องพยายามอย่างจริงจังเพื่อรับพระพรจากองค์พระผู้เป็นเจ้า ไม่ใช่เพราะพระองค์ไม่เต็มพระทัยที่จะประทานพระพรแก่เรา แต่เพราะเรายังไม่พร้อมที่จะรับพระพรนั้นต่างหาก พระบิดาของเราทรงเต็มพระทัยที่จะประทานพระวิญญาณบริสุทธิ์แก่ผู้ที่ทูลขอ มากยิ่งกว่าที่พ่อแม่ในโลกจะให้ของขวัญดีๆ แก่ลูกๆ ของตน แต่เป็นหน้าที่ของเราที่จะสารภาพบาป ถ่อมใจลง กลับใจใหม่ และอธิษฐานอย่างจริงจัง เพื่อให้เป็นไปตามเงื่อนไขที่พระเจ้าทรงสัญญาว่าจะประทานพระพรแก่เรา การฟื้นฟูจะเกิดขึ้นได้ก็ต่อเมื่อเราอธิษฐานขอเท่านั้น ในขณะที่ผู้คนขาดพระวิญญาณบริสุทธิ์ของพระเจ้าอย่างที่เป็นอยู่นี้ พวกเขาไม่สามารถซาบซึ้งในคำเทศนาที่ตรงตามพระวจนะได้ แต่เมื่อฤทธิ์เดชของพระวิญญาณสัมผัสจิตใจของพวกเขา คำเทศนาจะเกิดผลอย่างแน่นอน เมื่อคนที่มาร่วมประชุมของเราใช้วิจารณญาณอย่างรอบคอบตามการชี้นำจากพระวจนะ และการสำแดงของพระวิญญาณ พวกเขาจะได้รับประสบการณ์อันล้ำค่า และเมื่อกลับบ้านไป ก็จะพร้อมที่จะส่งผลดีต่อคนรอบข้าง {1SM 121.1}

**Comment by tonyquicktech** [comment]
Done
