### ISSUE TITLE
Fix inconsistent use of numbers in LBF

### ISSUE THREAD

**Issue by bountonw** [bountonw/translate#357]
Currently, there is inconsistency with the use of numbers, most are spelled out, some are written as Arabic numbers. These need to be made consistent, at least numbers 1-9. The  changes need to made both in the source files, and in Indesign. (At this stage of typesetting, we are not reimporting chapters, unless I am told that that is the best way.2

- [x] ./LBF11_th.md:ั้นอย่างแน่นอน มีความเป็นไปได้เพียง 2 ทาง คือ 1) จิตใจสามารถปฏิบัติได้ทั้
- [x] Indesign
- [x] ./LBF12_th.md:่ลบ เพราะพระบัญญัติทุกข้อสรุปอยู่ใน 2 ข้อใหญ่อันเป็นเชิงบวกว่า “จงรักองค์
- [x] Indesign
- [x] ./LBF13_th.md:บาปทั้งหลาย” (โคโลสี 1:12–14) มีอีก 2 ข้อความที่กล่าวถึงการทรงไถ่โดยพระโล
- [x] Indesign
- [x] ./LBF13_th.md:มีอยู่ 2 ประเด็นที่ควรสังเกตคือ เราได้รับการ
- [x] Indesign
- [x] ./LBF36_th.md:ดังนั้นจึงมีเหตุผลอยู่ 2 ประการว่าเพราะอะไรเราไม่สามารถถูกชำ
- [x] Indesign
- [x] ./LBF37_th.md:อให้สังเกตว่าคนป่วยและคนพิการในทั้ง 2 กรณีที่ยกมานี้ไม่จำเป็นต้องรักษาด่ว
- [x] Indesign
- [x] ./LBF39_th.md:ที่นำมาซึ่งความรอดนั้น เราจะพิจารณา 2 ประเด็นนี้ตามลำดับ {LBF 120.2}
- [x] Indesign
- [x] ./LBF39_th.md:มีประเด็นหลักอยู่ 2 ประเด็นคือ 1) การรอดพ้นจากความบาป แ
- [x] Indesign
- [x] ./LBF40_th.md:เดียวเพื่อให้ถึงเวลาที่กำหนด ในทั้ง 2 กรณีนี้เราจะไม่เติบโต นี่คือปัญหาให
- [x] Indesign
- [x] ./LBF42_th.md:ให้เราจดจำไว้อยู่ 2 ประการ คือ 1) การรักษาหญิงตกเลือดอย
- [x] Indesign

3

- [x] ./LBF01_th.md:จะโจมตีเราตลอดเวลา ครั้งที่ชาวฮีบรู 3 คนถูกโยนเข้าไปในเตาไฟนั้น ไฟไม่มีอำ
- [x] Indesign
- [x] ./LBF49_th.md:องพระเจ้า การประกาศข่าวของทูตสวรรค์ 3 องค์เป็นงานที่เราควรจะทำในขณะนี้ เพ
- [x] Indesign

6

- [x] ./LBF37_th.md:คภายใน 6 วันนั้น อย่าทำในวันสะบาโต’ แต่องค์พ
- [x] Indesign
- [x] ./LBF37_th.md:นวันสะบาโต จึงพูดกับฝูงชนว่า ‘มีถึง 6 วันสำหรับทำงาน จงมาและรับการรักษาโร
- [x] Indesign
- [x] ./LBF41_th.md:เมื่อพระเจ้าสร้างโลกสำเร็จใน 6 วัน พระองค์ “ทอดพระเนตรสิ่งทั้งปวงท
- [x] Indesign
- [x] ./LBF41_th.md:าศัยอยู่ในประตูเมืองของเจ้า เพราะใน 6 วันพระเจ้าทรงสร้างฟ้าและแผ่นดิน ทะเ
- [x] Indesign

**Comment by bountonw** [comment]
@tonyquicktech Can you make the changes in the source files here on git? We want the numbers to be spelled out. “สอง” instead of “2”, etc. Use one PR. I will take care of the Indesign side. The list above should be complete as those not listed are 1 Peter or John chapter 3 etc. Numbers 10 and above, we will continue to write as Arabic numerals.

**Comment by tonyquicktech** [comment]
@bountonw sure, I'll give it a shot.

**Comment by bountonw** [comment]
@tonyquicktech i have a PR open called LBF-typesetting. If you can use that, it will make it easier to avoid merge conflicts.

**Comment by tonyquicktech** [comment]
Ah okay, certainly, will do.

**Comment by tonyquicktech** [comment]
Btw, it seems the english source wasn't merged with main yet - should I make the english changes in my pending PR? @bountonw

**Comment by tonyquicktech** [comment]
Thai completed as per above - if there are more let me know and I can knock them out as well.

**Comment by bountonw** [comment]
The InDesign files have now been updated. Thank you, @tonyquicktech, for your help in updating the source files. This task will close automatically when PR #360 is merged.
