### ISSUE TITLE
Bury or resurrect dead branches

### ISSUE THREAD

**Issue by bountonw** [bountonw/translate#382]
@mattleff Can the `latex-pdfs` and `custom-artifact-name` branches be deleted or are they doing something useful? Are we or will we be needing them?

**Comment by mattleff** [comment]
@bountonw Nope, we don't need either. I deleted `custom-artifact-name` but you need to remove branch protection from `latex-pdfs` in repository Settings before it can be deleted.

**Comment by bountonw** [comment]
Resolved. Thank you.
