### ISSUE TITLE
Standardize text for “basedon” yaml in PP

### ISSUE THREAD

**Issue by bountonw** [bountonw/translate#398]
@mattleff Ideally we would handle the message of “basedon” yaml pragmatically upstream and only put the book, chapter, and verse in the yaml.

Edit: Currently this is being handled at least two different ways in the book and it will need to be standardized before publishing.

**Comment by mattleff** [comment]
@bountonw If we can always have `basedon` be only the book, chapter, & verse then I can easily make the generated output include the `ศึกษาควบคู่กับ` prefix. If that works for you I can go ahead and make a PR for that change.

**Comment by bountonw** [comment]
> @bountonw If we can always have `basedon` be only the book, chapter, & verse then I can easily make the generated output include the `ศึกษาควบคู่กับ` prefix. If that works for you I can go ahead and make a PR for that change.

Sounds good. We will need to clean it up from those chapters where is occurs.

**Comment by bountonw** [comment]
@mattleff Oops, we forgot about outliers. Some books of the bible start with numbers. There should be a space between the CONSTANT and the Scripture Reference when the Scripture Reference starts with a number.
