### ISSUE TITLE
Add CSPrajad fonts 

### ISSUE THREAD

**Issue by bountonw** [bountonw/translate#91]
* Delete CSPrajad fonts and fonts folder from PR #89  
* Create clean PR to add these fonts to `th/assets/fonts/CSPrajad/`

**Comment by tonyquicktech** [comment]
I don't have permission to delete files from that PR, but I will do the second item now.

**Comment by tonyquicktech** [comment]
Done @bountonw

**Comment by bountonw** [comment]
@tonyquicktech 

Make a new branch off of `latex-pdfs` , delete the files, and then create a pull request to merge back to `latex-pdfs`. (Make sure that your pull request is merging to the right branch.)

**Comment by bountonw** [comment]
Done with PR #108 to `main`  and PR #109 to `latex-pdfs`.
